include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

USEMODULE += sara_r410m
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
