# configuration file for run.py
boards:
  - "iotlab-m3"

profiles:
  no_extensions:
    config: ""
    label: "Baseline"
  c2c:
    config: "c2c_only.config"
    label: "C2C"
  c2c_auth:
    config: "c2c_auth.config"
    label: "C2C + Auth"

groups:
  # For now we ignore common OS and DTLS parts
  # ? "RIOT"
  # :
  #   modules:
  #     - ["core"]
  #     - ["boards"]
  #     - ["cpu"]
  #     - ["drivers"]
  #     - ["sys"]
  #     - ["pkg", "wakaama", "core", "er-coap-13"]
  #     - ["pkg", "tinydtls"]
  #     - ["unspecified"]
  #   config:
  #     hatch: "|/"
  #     base: true

  ? "LwM2M core"
  :
    modules:
      - ["pkg", "wakaama", "core"]
      - ["pkg", "wakaama", "contrib"]

      - ["pkg", "wakaama", "contrib", "objects"]

      # grouped under "utilities"
      - ["~", "pkg", "wakaama", "contrib", "objects", "common"]

      # grouped under "security object"
      - ["~", "pkg", "wakaama", "contrib", "objects", "security"]

      # grouped under "server object"
      - ["~", "pkg", "wakaama", "contrib", "objects", "server"]

      # grouped under "access control object"
      - ["~", "pkg", "wakaama", "contrib", "objects", "access_control"]

      # grouped under "other objects"
      - ["~", "pkg", "wakaama", "contrib", "objects"]

      # grouped under "connection handling"
      - ["~", "pkg", "wakaama", "contrib", "lwm2m_client"]
      - ["~", "pkg", "wakaama", "contrib", "lwm2m_client_connection"]

      # grouped under "client to client"
      - ["~", "pkg", "wakaama", "core", "client_to_client"]

      # grouped under "authorization request"
      - ["~", "pkg", "wakaama", "core", "auth_request"]

      # grouped under "coap"
      - ["~", "pkg", "wakaama", "core", "er-coap-13"]

      # grouped under "utils"
      - ["~", "pkg", "wakaama", "core", "utils"]
      - ["~", "pkg", "wakaama", "core", "uri"]
      - ["~", "pkg", "wakaama", "core", "packet"]
      - ["~", "pkg", "wakaama", "core", "objects"]
      - ["~", "pkg", "wakaama", "core", "tinycbor"]

    config:
      hatch: "/"

  ? "Utilities"
  :
    modules:
      - ["pkg", "wakaama", "core", "utils"]
      - ["pkg", "wakaama", "core", "uri"]
      - ["pkg", "wakaama", "core", "packet"]
      - ["pkg", "wakaama", "core", "objects"]
      - ["pkg", "wakaama", "core", "tinycbor"]
      - ["pkg", "wakaama", "contrib", "objects", "common"]

      # only needed for shell
      - ["~", "pkg", "wakaama", "core", "uri", "lwm2m_stringToUri"]

      # grouped under "client to client"
      - ["~", "pkg", "wakaama", "core", "objects", "object_getClients"]
    config:
      hatch: "|"

  ? "Access ctrl. object"
  :
    modules:
      - ["pkg", "wakaama", "contrib", "objects", "access_control"]
    config:
      hatch: "\\."

  ? "Security object"
  :
    modules:
      - ["pkg", "wakaama", "contrib", "objects", "security"]
    config:
      hatch: "x"

  ? "Server object"
  :
    modules:
      - ["pkg", "wakaama", "contrib", "objects", "server"]
    config:
      hatch: "--"

  ? "Peer handling"
  :
    modules:
      - ["pkg", "wakaama", "contrib", "lwm2m_client"]
      - ["pkg", "wakaama", "contrib", "lwm2m_client_connection"]

      # grouped under "client to client"
      - ["~", "pkg", "wakaama", "contrib", "lwm2m_client", "lwm2m_client_read"]
      - ["~", "pkg", "wakaama", "contrib", "lwm2m_client", "lwm2m_client_observe"]
    config:
      hatch: "\\"

  ? "Client-to-client"
  :
    modules:
      - ["pkg", "wakaama", "core", "client_to_client"]
      - ["pkg", "wakaama", "contrib", "lwm2m_client", "lwm2m_client_read"]
      - ["pkg", "wakaama", "contrib", "lwm2m_client", "lwm2m_client_observe"]
      - ["pkg", "wakaama", "core", "objects", "object_getClients"]
    config:
      hatch: "."

  ? "Authorization"
  :
    modules:
      - ["pkg", "wakaama", "core", "auth_request"]
    config:
          hatch: "+"

# # some plot configuration
plots:
  config:
    hatch:
      linewidth: 0.5
    label:
      width: 10
