ifneq (,$(filter arduino,$(USEMODULE)))
  FEATURES_OPTIONAL += periph_i2c
  FEATURES_OPTIONAL += periph_spi
  FEATURES_REQUIRED += periph_uart
  FEATURES_REQUIRED += cpp
  SKETCH_MODULE ?= arduino_sketches
  USEMODULE += $(SKETCH_MODULE)
endif

ifneq (,$(filter eepreg,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eeprom
endif

ifneq (,$(filter fmt_table,$(USEMODULE)))
  USEMODULE += fmt
endif

ifneq (,$(filter i2c_scan,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter prng_fortuna,$(USEMODULE)))
  USEMODULE += crypto_aes
endif

ifneq (,$(filter crypto_aes_%,$(USEMODULE)))
  USEMODULE += crypto_aes
endif

ifneq (,$(filter crypto_%,$(USEMODULE)))
  USEMODULE += crypto
endif

ifneq (,$(filter crypto_mode_%,$(USEMODULE)))
  USEMODULE += crypto_mode
endif

ifneq (,$(filter crypto_mode_aes_%,$(USEMODULE)))
  USEMODULE += crypto_aes
endif

ifneq (,$(filter crypto_mode_aes_ctr,$(USEMODULE)))
  USEMODULE += crypto_mode_ctr
endif

ifneq (,$(filter crypto_mode_aes_cbc,$(USEMODULE)))
  USEMODULE += crypto_mode_cbc
endif

ifneq (,$(filter rtt_cmd,$(USEMODULE)))
  FEATURES_REQUIRED += periph_rtt
endif

ifneq (,$(filter trace,$(USEMODULE)))
  USEMODULE += xtimer
endif

ifneq (,$(filter shell_commands,$(USEMODULE)))
  ifneq (,$(filter dfplayer,$(USEMODULE)))
    USEMODULE += auto_init_multimedia
    USEMODULE += fmt
  endif
endif

include $(RIOTBASE)/sys/test_utils/Makefile.dep
