sources := $(filter-out init.c mbox.c msg.c msg_bus.c panic.c thread_flags.c,$(notdir $(wildcard $(current_dir)/*.c)))

src-y += $(sources:%.c=$(current_dir)/%.c)

src-$(MOD_CORE_INIT) += $(current_dir)/init.c
src-$(MOD_CORE_MBOX) += $(current_dir)/mbox.c
src-$(MOD_CORE_MSG) += $(current_dir)/msg.c
src-$(MOD_CORE_MSG_BUS) += $(current_dir)/msg_bus.c
src-$(MOD_CORE_PANIC) += $(current_dir)/panic.c
src-$(MOD_CORE_THREAD_FLAGS) += $(current_dir)/thread_flags.c
