INCLUDES += -I$(PKGDIRBASE)/nrfxlib/crypto/nrf_cc310_platform/include
INCLUDES += -I$(RIOTCPU)/$(CPU)/include/vendor
ARCHIVES += $(BINDIR)/libnrf_cc310_platform_0.9.12.a

PSEUDOMODULES += nrfxlib_interrupt
